name: Test with upstream linkml
on:
  pull_request_review:
    types: [ submitted ]
  workflow_dispatch:

jobs:
  test_upstream:
    if: github.event_name == 'workflow_dispatch' || github.event.review.state == 'APPROVED'
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
        exclude:
          - os: windows-latest
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.11"
    runs-on: ${{ matrix.os }}
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true

    steps:

      - name: checkout upstream
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: linkml/linkml
          path: linkml
          ref: main
          fetch-depth: 0

      - name: checkout linkml-runtime
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          # don't specify repository like this or else we won't get pull request branches correctly
          # repository: linkml/linkml-runtime
          path: linkml-runtime
          fetch-depth: 0

      - name: Ensure tags if not run from main repo
        if: github.repository != 'linkml/linkml-runtime'
        working-directory: linkml-runtime
        run: |
          git remote add upstream https://github.com/linkml/linkml-runtime
          git fetch upstream --tags

      - name: set up python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pipx install poetry

      # We install poetry-dynamic-versioning into pipx because the automatic installallation
      # by poetry 2.x triggers a Windows issue https://github.com/pypa/installer/issues/260
      - name: Install poetry-dynamic-versioning
        if: runner.os == 'Windows'
        run:
          pipx inject poetry poetry-dynamic-versioning

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: linkml/.venv
          key: venv-${{ matrix.python-version }}-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      # make extra sure we're removing any old version of linkml-runtime that exists
      - name: uninstall potentially cached linkml-runtime
        working-directory: linkml
        run: poetry run pip uninstall linkml-runtime

      # we are not using linkml-runtime's lockfile, but simulating what will happen
      # when we merge this and update linkml's lockfile
      - name: add linkml-runtime to lockfile
        working-directory: linkml
        run: poetry add ../linkml-runtime

      # note that we run the installation step always, even if we restore a venv,
      # the cache will restore the old version of linkml-runtime, but the lockfile
      # will only store the directory dependency (and thus will reinstall it)
      # the cache will still speedup the rest of the installation
      - name: install linkml
        working-directory: linkml
        run: poetry install --no-interaction -E tests

      - name: print linkml-runtime version
        working-directory: linkml
        run: poetry run python -c 'import linkml_runtime; from importlib.metadata import version; print(linkml_runtime.__file__); print(version("linkml_runtime"))'

      - name: run tests
        shell: bash
        working-directory: linkml
        run: poetry run python -m pytest --with-slow



